
import { Injectable } from '@angular/core';
import {Http, Response} from '@angular/http'
import { Observable } from 'rxjs/Observable';
import {TreeData} from './treeData';
//import * as Rx from 'rxjs';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import 'rxjs/add/observable/of';

export interface ITreeListService {
    getTreeData();
}

@Injectable()
export class TreeListService implements ITreeListService{

    constructor (private _http: Http) {}
    private treeUrl = '/api/treelist';

    getTreeData() : Observable<TreeData[]>{
        let aa = this._http.get(this.treeUrl);
        let bb = aa.map((res:Response) => res.json());
        
        return this._http.get(this.treeUrl)
                    .map((res:Response) => res.json())
                    .catch((error:any) => Observable.throw(error.json().error || 'Server error'));
     }
}

@Injectable()
export class  MockTreeListService implements ITreeListService{
    getTreeData() : Observable<TreeData[]>{
        
        let jsonString =
        [
            {
                "ScientificName": "Pongamia pinnata",
                "CommonName": "Pongam1",
                "Order1":"1",
                "Order2":"11",
                "Order3": 111,
                "FlowerColor": "white, purple, pink",
                "FlowerSize": "small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "brown",
                "FruitSize": "small",
                "FruitShape": "Oval woody pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/1.JPG", "../assets/1001.JPG","../assets/1002.JPG","../assets/1003.JPG"], "ImageCredit": ["Dinesh Valke","Dinesh Valke","J M Garg","J M Garg"], 
		"Description": "Its a popular city tree as its not nibbled by goats and provides good shade! Seed yields oil which is used for soap making and as an illuminant. The oil is also used to treat scabies, herpes and rheumatism. The fallen flowers can be collected and used as a good manure for plants.",
                "RareTrees": ""
            },
            {
                "ScientificName": "Spathodea campanulata",
                "CommonName": "African tulip tree",
                "Order1":"1",
                "Order2":"11",
                "Order3": 112,
                "FlowerColor": "red",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "green, brown",
                "FruitSize": "large",
                "FruitShape": "long woody pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/2.JPG","../assets/201.JPG"], "ImageCredit": ["A Ajit", "A Ajit"], 
		"Description": "The flower bud contains water because of which children use it as a toy to squirt water on each other! This tree is often mistaken as the flame of the forest tree by many. The hard central part of the fruit contains poisonous substance which is used by hunters in Africa to kill animals. The flower attracts birds like Rose ringed parakeets, Mynas, bulbuls and Starlings.",
                "RareTrees": ""
            },
            {
                "ScientificName": "Jacaranda mimosifolia",
                "CommonName": "Jacaranda",
                "Order1":"1",
                "Order2":"11",
                "Order3": 113,
                "FlowerColor": "Purple, blue",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "brown, black",
                "FruitSize": "medium",
                "FruitShape": "circular woody capsule",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/3.JPG","../assets/301.JPG","../assets/302.JPG"], "ImageCredit": ["A Ajit","Dinesh Valke","Kolumbusjogger"], 
		"Description": "Its an ornamental tree native to South America and is grown all over the world because of it profuse flowering. Purple panic is a term for student stress during the period late spring and early summer used by students in south east Queensland. The purple refers to the colour of the flowers of Jacaranda trees which bloom at that time! The panic refers to the need to be completing assignments and studying for final exams.",
                "RareTrees": ""
            },
            {
                "ScientificName": "Peltophorum pterocarpum",
                "CommonName": "Copperpod",
                "Order1":"1",
                "Order2":"11",
                "Order3": 114,
                "FlowerColor": "yellow",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Copper, rust",
                "FruitSize": "medium",
                "FruitShape": "Oval woody pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/4.JPG","../assets/402.JPG"], "ImageCredit": ["A Ajit","Forest & Kim Starr"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Tabebuia rosea",
                "CommonName": "Rosy trumpet tree",
                "Order1":"1",
                "Order2":"11",
                "Order3": 115,
                "FlowerColor": "pink",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown",
                "FruitSize": "medium",
                "FruitShape": "long woody pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/5.JPG","../assets/501.JPG","../assets/502.JPG"], 
                "ImageCredit": ["A Ajit","A Ajit","Dinesh Valke"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Delonix regia",
                "CommonName": "Gulmohar",
                "Order1":"1",
                "Order2":"11",
                "Order3": 116,
                "FlowerColor": "red",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown",
                "FruitSize": "large",
                "FruitShape": "long woody pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/6.JPG","../assets/601.JPG","../assets/602.JPG"],
                "ImageCredit": ["A Ajit","A Ajit","J M Garg"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Syzigium cumini",
                "CommonName": "Jamun",
                "Order1":"1",
                "Order2":"12",
                "Order3": 121,
                "FlowerColor": "white",
                "FlowerSize": "small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "green,pink, black, purple",
                "FruitSize": "medium",
                "FruitShape": "Ovoid fleshy berry",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/7.JPG","../assets/701.JPG"], "ImageCredit": ["A Ajit","Judgefloro"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },  
            {
                "ScientificName": "Acacia auriculiformis",
                "CommonName": "Earpod wattle",
                "Order1":"1",
                "Order2":"12",
                "Order3": 122,
                "FlowerColor": "yellow",
                "FlowerSize": "small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown",
                "FruitSize": "medium",
                "FruitShape": "Coiled woody pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/8.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Eucalyptus tereticornis",
                "CommonName": "Eucalyptus",
                "Order1":"1",
                "Order2":"12",
                "Order3": 123,
                "FlowerColor": "white",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "white",
                "FruitSize": "small",
                "FruitShape": "conical woody capsule",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/9.jpeg"], "ImageCredit": ["Ethel Aardvark"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Thespesia populnea",
                "CommonName": "Bhendi tree",
                "Order1":"1",
                "Order2":"12",
                "Order3": 124,
                "FlowerColor": "yellow, pink, red",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "green, black",
                "FruitSize": "medium",
                "FruitShape": "globose capsule",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/10.JPG","../assets/1001-E.JPG","../assets/1002-E.JPG"], "ImageCredit": ["J M Garg", "A Ajit","Daderot"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Tecoma stans",
                "CommonName": "Yellow bells",
                "Order1":"1",
                "Order2":"12",
                "Order3": 126,
                "FlowerColor": "yellow",
                "FlowerSize": "large",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "green, brown",
                "FruitSize": "medium",
                "FruitShape": "narrow flatish pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/11.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Leucaena leucocephela",
                "CommonName": "Wild tamarind",
                "Order1":"1",
                "Order2":"12",
                "Order3": 127,
                "FlowerColor": "white, creamy",
                "FlowerSize": "small,large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "reddish brown",
                "FruitSize": "large",
                "FruitShape": "long woody pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/12.JPG","../assets/1201.JPG"], "ImageCredit": ["Dinesh Valke","Dinesh Valke"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Senna siamea",
                "CommonName": "Siamese cassia",
                "Order1":"1",
                "Order2":"13",
                "Order3": 131,
                "FlowerColor": "yellow",
                "FlowerSize": "small, large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown",
                "FruitSize": "large",
                "FruitShape": "long flattish narrow pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/13.JPG","../assets/1301.JPG"], "ImageCredit": ["J M Garg","J M Garg"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Bauhinia purpurea",
                "CommonName": "Purple orchid tree",
                "Order1":"1",
                "Order2":"13",
                "Order3": 132,
                "FlowerColor": "purple, pink",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "green, maroon",
                "FruitSize": "large",
                "FruitShape": "long flattish narrow pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/14.JPG"], "ImageCredit": ["Revati Sarnaik"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Tabebuia aurea",
                "CommonName": "Tree of gold",
                "Order1":"1",
                "Order2":"13",
                "Order3": 133,
                "FlowerColor": "yellow",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Green",
                "FruitSize": "medium",
                "FruitShape": "long dry pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/15.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Muntingia calabura",
                "CommonName": "Singapore cherry",
                "Order1":"1",
                "Order2":"13",
                "Order3": 134,
                "FlowerColor": "white",
                "FlowerSize": "small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "green, red",
                "FruitSize": "small",
                "FruitShape": "round berry",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/16.JPG","../assets/1601.JPG"], "ImageCredit": ["Dinesh Valke","Dinesh Valke"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Markhamia lutea",
                "CommonName": "Nile tulip tree",
                "Order1":"1",
                "Order2":"14",
                "Order3": 141,
                "FlowerColor": "yellow",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "brown",
                "FruitSize": "large",
                "FruitShape": "long flatish wavy pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/17.JPG","../assets/1701.JPG"], "ImageCredit": ["J M Garg","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Laegerstroemia speciosa",
                "CommonName": "Jarul",
                "Order1":"2",
                "Order2":"21",
                "Order3": 211,
                "FlowerColor": "purple, pink",
                "FlowerSize": "Large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "brown",
                "FruitSize": "small",
                "FruitShape": "Spherical woody splitting open",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/18.JPG","../assets/1801.JPG","../assets/1802.JPG"], "ImageCredit": ["A Ajit","A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Albizia saman",
                "CommonName": "Rain tree",
                "Order1":"2",
                "Order2":"21",
                "Order3": 212,
                "FlowerColor": "Pink, white",
                "FlowerSize": "Large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "brown",
                "FruitSize": "large",
                "FruitShape": "long fleshy pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/19.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Polyalthia longifolia",
                "CommonName": "mast tree",
                "Order1":"2",
                "Order2":"21",
                "Order3": 213,
                "FlowerColor": "green, white",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green, purple",
                "FruitSize": "small",
                "FruitShape": "round berry like",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/20.JPG","../assets/2001.JPG"], "ImageCredit": ["Dinesh Valke","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Millingtonia hortensis",
                "CommonName": "Indian cork tree",
                "Order1":"2",
                "Order2":"21",
                "Order3": 214,
                "FlowerColor": "white",
                "FlowerSize": "small",
                "FlowerSmell": "Highly Fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "green,brown",
                "FruitSize": "large",
                "FruitShape": "long narrow flattened capsule",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/2101.JPG","../assets/21.JPG"], "ImageCredit": ["J M Garg","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Mangifera indica",
                "CommonName": "Mango",
                "Order1":"2",
                "Order2":"22",
                "Order3": 215,
                "FlowerColor": "Green, white",
                "FlowerSize": "small",
                "FlowerSmell": "strong smell",
                "ClusterOrSingle": "C",
                "FruitColor": "green,yellow",
                "FruitSize": "large",
                "FruitShape": "Large round fleshy",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/22.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Grevillea robusta",
                "CommonName": "Silveroak",
                "Order1":"2",
                "Order2":"21",
                "Order3": 216,
                "FlowerColor": "orange, yellow",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "brown",
                "FruitSize": "small",
                "FruitShape": "small woody pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/23.JPG"], "ImageCredit": ["Alvesgaspar"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Handroanthus impetiginosus",
                "CommonName": "Pink trumpet tree",
                "Order1":"2",
                "Order2":"21",
                "Order3": 217,
                "FlowerColor": "Pink",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "brown",
                "FruitSize": "medium",
                "FruitShape": "long flat dry pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/24.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Senna spectabilis",
                "CommonName": "Spectacular cassia",
                "Order1":"2",
                "Order2":"22",
                "Order3": 221,
                "FlowerColor": "yellow",
                "FlowerSize": "large,small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown",
                "FruitSize": "large",
                "FruitShape": "long cylindrical dry pods",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/25.JPG"], "ImageCredit": ["A. J. T. Johnsingh, WWF-India and NCF"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Swietenia macrophylla",
                "CommonName": "Large leaved Mahagony",
                "Order1":"2",
                "Order2":"22",
                "Order3": 222,
                "FlowerColor": "Green",
                "FlowerSize": "small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "brown",
                "FruitSize": "large",
                "FruitShape": "woody capsule",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/26.JPG","../assets/2601.JPG"], "ImageCredit": ["A Ajit","J M Garg"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Pithecelobium dulce",
                "CommonName": "Manila tamarind",
                "Order1":"2",
                "Order2":"22",
                "Order3": 223,
                "FlowerColor": "white, creamy",
                "FlowerSize": "small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "green, red",
                "FruitSize": "small",
                "FruitShape": "long coiled flattened pod",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/27.JPG","../assets/2701.JPG"], "ImageCredit": ["A Ajit","Dinesh Valke"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Plumeria rubra",
                "CommonName": "Champa",
                "Order1":"2",
                "Order2":"22",
                "Order3": 224,
                "FlowerColor": "white, pink, red, yellow",
                "FlowerSize": "large,small",
                "FlowerSmell": "highly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "green",
                "FruitSize": "medium",
                "FruitShape": "paired leathery pods",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/28.JPG","../assets/2801.JPG"], "ImageCredit": ["Sivaraj", "A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later.",
                "RareTrees": ""
            },
            {
                "ScientificName": "Cocos nucifera",
                "CommonName": "Coconut tree",
                "Order1":"2",
                "Order2":"22",
                "Order3": 225,
                "FlowerColor": "green, yellow",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown",
                "FruitSize": "large",
                "FruitShape": "Spherical",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/29.JPG","../assets/2901.JPG","../assets/2902.JPG"], 
                "ImageCredit": ["Sajanjs at Malayalam Wikipedia","Vengolis","Alok Kumar"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Terminalia arjuna",
                "CommonName": "Arjuna",
                "Order1":"2",
                "Order2":"23",
                "Order3": 231,
                "FlowerColor": "white, creamy",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown",
                "FruitSize": "medium",
                "FruitShape": "Woody nut with wings",
                "EdibleFruit": "N",
                "FeatureTags": "Star shaped",
                "Image": [ "../assets/30.JPG","../assets/3001.JPG"], "ImageCredit": ["A Ajit","J M Garg"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Terminalia catappa",
                "CommonName": "Tropical almond",
                "Order1":"2",
                "Order2":"23",
                "Order3": 232,
                "FlowerColor": "white, creamy",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green, red",
                "FruitSize": "medium",
                "FruitShape": "Rounded elongated fleshy",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/31.JPG","../assets/3101.JPG"], "ImageCredit": ["Franz Xaver","Dinesh Valke"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Plumeria obtusa",
                "CommonName": "White frangipani",
                "Order1":"2",
                "Order2":"23",
                "Order3": 233,
                "FlowerColor": "white, yellow",
                "FlowerSize": "large,small",
                "FlowerSmell": "Highly Fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "green, grey",
                "FruitSize": "medium",
                "FruitShape": "Dark shiny long pods",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/32.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Ficus benghalensis",
                "CommonName": "Banyan",
                "Order1":"2",
                "Order2":"23",
                "Order3": 234,
                "FlowerColor": "None",
                "FlowerSize": "None",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green, red",
                "FruitSize": "medium",
                "FruitShape": "round berry",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/3301.JPG","../assets/33.JPG"], "ImageCredit": ["A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Ficus religiosa",
                "CommonName": "Peepal",
                "Order1":"2",
                "Order2":"23",
                "Order3": 235,
                "FlowerColor": "None",
                "FlowerSize": "None",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "red, purple, black",
                "FruitSize": "small",
                "FruitShape": "round berry",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/34.JPG","../assets/3401.JPG"], "ImageCredit": ["A Ajit","Dinesh Valke"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Ficus racemosa",
                "CommonName": "Cluster fig tree",
                "Order1":"2",
                "Order2":"23",
                "Order3": 236,
                "FlowerColor": "None",
                "FlowerSize": "None",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green,red",
                "FruitSize": "medium",
                "FruitShape": "round berry",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/35.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Phyllanthus acidus",
                "CommonName": "Star goosbery",
                "Order1":"2",
                "Order2":"23",
                "Order3": 237,
                "FlowerColor": "red",
                "FlowerSize": "small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "green, white",
                "FruitSize": "small",
                "FruitShape": "winged fleshy berry",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/36.JPG","../assets/3601.JPG"], 
                "ImageCredit": ["PJeganathan", "A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Tabebuia palida",
                "CommonName": "White trumpet tree",
                "Order1":"2",
                "Order2":"23",
                "Order3": 238,
                "FlowerColor": "white",
                "FlowerSize": "Large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "green,brown",
                "FruitSize": "medium",
                "FruitShape": "long flat dry pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/37.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Cassia javanica",
                "CommonName": "Java cassia",
                "Order1":"2",
                "Order2":"23",
                "Order3": 239,
                "FlowerColor": "Pink, white",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green,brown",
                "FruitSize": "medium",
                "FruitShape": "long cylindrical dry pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/38.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Alstonia macrophylla",
                "CommonName": "Batino",
                "Order1":"2",
                "Order2":"23",
                "Order3": 240,
                "FlowerColor": "white",
                "FlowerSize": "small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown",
                "FruitSize": "medium",
                "FruitShape": "Thin bean like",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/39.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Ceiba pentandra",
                "CommonName": "Kapok",
                "Order1":"2",
                "Order2":"24",
                "Order3": 241,
                "FlowerColor": "Red",
                "FlowerSize": "Large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "green, brown",
                "FruitSize": "medium",
                "FruitShape": "Large capsule pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/40.JPG","../assets/4001.JPG"], "ImageCredit": ["J M Garg", "Velela"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Cassia grandis",
                "CommonName": "Brazilian cassia",
                "Order1":"2",
                "Order2":"24",
                "Order3": 242,
                "FlowerColor": "Pink, orange",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown",
                "FruitSize": "medium",
                "FruitShape": "long cylindrical dry pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/41.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Sterculia foetida",
                "CommonName": "Wild almond",
                "Order1":"2",
                "Order2":"24",
                "Order3": 243,
                "FlowerColor": "Red",
                "FlowerSize": "small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "Green, Red, Brown",
                "FruitSize": "Big",
                "FruitShape": "Spherical woody splitting open",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/42.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Cassia fistula",
                "CommonName": "Indian laburnum",
                "Order1":"3",
                "Order2":"31",
                "Order3": 311,
                "FlowerColor": "Yellow",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green,brown",
                "FruitSize": "medium",
                "FruitShape": "long cylindrical dry pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/43.JPG","../assets/4301.JPG","../assets/4302.JPG"], "ImageCredit": ["A Ajit","A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Tamarindus indicus",
                "CommonName": "Tamarind",
                "Order1":"3",
                "Order2":"31",
                "Order3": 312,
                "FlowerColor": "Red, Yellow",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Green, Brown",
                "FruitSize": "medium",
                "FruitShape": "Long bulging dry pod",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/44.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Callistemon citrinus",
                "CommonName": "Bottle brush",
                "Order1":"3",
                "Order2":"31",
                "Order3": 313,
                "FlowerColor": "Red",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Brown",
                "FruitSize": "small",
                "FruitShape": "Many small spherical globules",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/45.JPG"], "ImageCredit": ["Dinesh Valke"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Azadirachta indica",
                "CommonName": "Neem",
                "Order1":"3",
                "Order2":"32",
                "Order3": 321,
                "FlowerColor": "white, creamy",
                "FlowerSize": "small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "green, purple",
                "FruitSize": "small",
                "FruitShape": "long fleshy pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/46.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Michelia champaka",
                "CommonName": "Champak",
                "Order1":"3",
                "Order2":"32",
                "Order3": 322,
                "FlowerColor": "yellow, creamy, orange",
                "FlowerSize": "large,small",
                "FlowerSmell": "highly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "Green, Red",
                "FruitSize": "medium",
                "FruitShape": "Spherical fleshy",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/47.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Caesalpinia pulcherima",
                "CommonName": "Peacock flower",
                "Order1":"3",
                "Order2":"32",
                "Order3": 323,
                "FlowerColor": "Red, yellow",
                "FlowerSize": "Large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green,brown",
                "FruitSize": "Large",
                "FruitShape": "long flat dry pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/48.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Tectona grandis",
                "CommonName": "Teak",
                "Order1":"3",
                "Order2":"32",
                "Order3": 324,
                "FlowerColor": "white, creamy",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown, black",
                "FruitSize": "medium",
                "FruitShape": "round winged pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/49.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Parkia biglandulosa",
                "CommonName": "badminton ball",
                "Order1":"3",
                "Order2":"32",
                "Order3": 325,
                "FlowerColor": "white, creamy",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "green, brown, black",
                "FruitSize": "medium",
                "FruitShape": "long flat dry pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/50.JPG","../assets/5001.JPG"], "ImageCredit": ["A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Kigelia africana",
                "CommonName": "Sausage tree",
                "Order1":"3",
                "Order2":"32",
                "Order3": 326,
                "FlowerColor": "Red",
                "FlowerSize": "large",
                "FlowerSmell": "Bad smell",
                "ClusterOrSingle": "S",
                "FruitColor": "Brown",
                "FruitSize": "large",
                "FruitShape": "long cylindrical fleshy pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/51.JPG","../assets/5101.JPG"], 
                "ImageCredit": ["Akashanthoney", "Jessp"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Anthocephelus kadamba",
                "CommonName": "Kadamba",
                "Order1":"3",
                "Order2":"32",
                "Order3": 327,
                "FlowerColor": "Orange, white, yellow",
                "FlowerSize": "large",
                "FlowerSmell": "highly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "orange, yellow",
                "FruitSize": "medium",
                "FruitShape": "Spherical fleshy",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/52.JPG"], "ImageCredit": ["Balaram Mahalder"], 
		        "Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Melaleuca bracteata",
                "CommonName": "Black tea tree",
                "Order1":"3",
                "Order2":"32",
                "Order3": 328,
                "FlowerColor": "White",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "brown, black",
                "FruitSize": "small",
                "FruitShape": "Spherical dry",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/53.JPG","../assets/5301.JPG"], 
                "ImageCredit": ["Daderot", "Geoff Derrin"], 
		        "Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Artocarpus hetrophyllus",
                "CommonName": "Jackfruit",
                "Order1":"3",
                "Order2":"33",
                "Order3": 331,
                "FlowerColor": "white, green",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green",
                "FruitSize": "large",
                "FruitShape": "Large, lumpy, barrel or pear shaped fleshy",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/54.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Dalbergia sisso",
                "CommonName": "Indian rosewood",
                "Order1":"3",
                "Order2":"33",
                "Order3": 332,
                "FlowerColor": "creamy, yellow",
                "FlowerSize": "small",
                "FlowerSmell": "Mildly Fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown",
                "FruitSize": "medium",
                "FruitShape": "Thin flat pods",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/55.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Punica granatum",
                "CommonName": "Anar",
                "Order1":"3",
                "Order2":"33",
                "Order3": 333,
                "FlowerColor": "Red",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "Red, green",
                "FruitSize": "Medium",
                "FruitShape": "Spherical fleshy",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/56.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Ficus benjamina",
                "CommonName": "Weeping fig",
                "Order1":"3",
                "Order2":"33",
                "Order3": 334,
                "FlowerColor": "None",
                "FlowerSize": "None",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Red,green,yellow",
                "FruitSize": "small",
                "FruitShape": "round berry",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/57.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Casuarina equisetifolia",
                "CommonName": "Whistling pine",
                "Order1":"3",
                "Order2":"33",
                "Order3": 335,
                "FlowerColor": "Red",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Brown",
                "FruitSize": "small",
                "FruitShape": "Ovoid dry",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/58.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Bauhinia variegata",
                "CommonName": "Kachnar",
                "Order1":"3",
                "Order2":"33",
                "Order3": 336,
                "FlowerColor": "purple, pink",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "green, maroon",
                "FruitSize": "large",
                "FruitShape": "long flattish narrow pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/59.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": "Y"
            },
            {
                "ScientificName": "Acacia nilotica",
                "CommonName": "Babool",
                "Order1":"3",
                "Order2":"33",
                "Order3": 337,
                "FlowerColor": "Yellow",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "green",
                "FruitSize": "medium",
                "FruitShape": "Beaded pods",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/60.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Ziziphus mauritiana",
                "CommonName": "Indian Jujube(Ber)",
                "Order1":"3",
                "Order2":"33",
                "Order3": 338,
                "FlowerColor": "white, green",
                "FlowerSize": "small",
                "FlowerSmell": "Bad smell",
                "ClusterOrSingle": "C",
                "FruitColor": "Green, Brown",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/61.JPG","../assets/6101.JPG"], "ImageCredit": ["A Ajit", "Wibowo Djatmiko"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Annona squamosa",
                "CommonName": "Sitaphal",
                "Order1":"3",
                "Order2":"33",
                "Order3": 339,
                "FlowerColor": "white, green",
                "FlowerSize": "large",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "Green, Brown",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/6201.JPG","../assets/62.JPG"], 
                "ImageCredit": ["J M Garg","Meneerke bloem"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Annona reticulata",
                "CommonName": "Ramphal",
                "Order1":"3",
                "Order2":"33",
                "Order3": 340,
                "FlowerColor": "white, green",
                "FlowerSize": "large",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": ["../assets/6301.JPG","../assets/63.JPG"], "ImageCredit": ["Dinesh Valke","Ks.Mini"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Milletia peguensis",
                "CommonName": "Moulmein rosewood",
                "Order1":"4",
                "Order2":"41",
                "Order3": 411,
                "FlowerColor": "Purple, pink",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/64.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Gmelina arborea",
                "CommonName": "Gamhar",
                "Order1":"4",
                "Order2":"41",
                "Order3": 412,
                "FlowerColor": "Red, Orange, Yellow",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/65.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Nyctanthes arbor-tristis",
                "CommonName": "Night Jasmine",
                "Order1":"4",
                "Order2":"41",
                "Order3": 413,
                "FlowerColor": "White, Red, Orange",
                "FlowerSize": "small",
                "FlowerSmell": "highly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/66.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Psidium guajava",
                "CommonName": "Guava tree",
                "Order1":"4",
                "Order2":"42",
                "Order3": 421,
                "FlowerColor": "White",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/67.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Erythrina stricta var suberosa",
                "CommonName": "Corky Coral tree",
                "Order1":"4",
                "Order2":"42",
                "Order3": 422,
                "FlowerColor": "Red",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/68.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Madhuca longifolia",
                "CommonName": "Mahua",
                "Order1":"4",
                "Order2":"42",
                "Order3": 423,
                "FlowerColor": "Brown, Green",
                "FlowerSize": "large,small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/69.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Yellow oleander",
                "CommonName": "Thevetia peruviana",
                "Order1":"4",
                "Order2":"42",
                "Order3": 424,
                "FlowerColor": "Yellow",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": ["../assets/70.JPG","../assets/7001.JPG"], "ImageCredit": ["Vinayaraj","Raffi Kojian"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Saraca asoka",
                "CommonName": "Sita ashok",
                "Order1":"4",
                "Order2":"42",
                "Order3": 425,
                "FlowerColor": "Red, Orange",
                "FlowerSize": "small",
                "FlowerSmell": "Fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/71.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Albizia lebbeck",
                "CommonName": "Womens tongue tree",
                "Order1":"4",
                "Order2":"42",
                "Order3": 426,
                "FlowerColor": "white, yellow, green",
                "FlowerSize": "large",
                "FlowerSmell": "highly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/72.JPG","../assets/7202.JPG","../assets/7201.JPG"], "ImageCredit": ["A Ajit","Dinesh Valke","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Ficus drupacea",
                "CommonName": "Mysore fig",
                "Order1":"4",
                "Order2":"42",
                "Order3": 427,
                "FlowerColor": "None",
                "FlowerSize": "None",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Yellow",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/73.JPG","../assets/7301.JPG"], "ImageCredit": ["A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Gliricidia sepium",
                "CommonName": "Gliricidia",
                "Order1":"4",
                "Order2":"42",
                "Order3": 428,
                "FlowerColor": "Pink, Purple",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/74.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Couroupita guianensis",
                "CommonName": "Cannon Ball Tree",
                "Order1": "",
                "Order2":"",
                "Order3": 429,
                "FlowerColor": "Red",
                "FlowerSize": "large",
                "FlowerSmell": "Highly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "Brown",
                "FruitSize": "large",
                "FruitShape": "Spherical",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/75.JPG","../assets/7501.JPG"], 
                "ImageCredit": ["A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Ficus elastica",
                "CommonName": "Indian rubber tree",
                "Order1":"4",
                "Order2":"43",
                "Order3": 431,
                "FlowerColor": "None",
                "FlowerSize": "None",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Green",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/76.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Terminalia bellirica",
                "CommonName": "Baheda",
                "Order1":"4",
                "Order2":"43",
                "Order3": 432,
                "FlowerColor": "white, green",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Green, Brown",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/77.JPG","../assets/7701.JPG","../assets/7702.JPG"], "ImageCredit": ["A Ajit","A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Santalum album",
                "CommonName": "Sandalwood",
                "Order1":"4",
                "Order2":"43",
                "Order3": 433,
                "FlowerColor": "Red",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green,pink, black, purple",
                "FruitSize": "small",
                "FruitShape": "Ovoid fleshy berry",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/78.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Mimusops elengi",
                "CommonName": "Maulsari",
                "Order1":"4",
                "Order2":"43",
                "Order3": 434,
                "FlowerColor": "White",
                "FlowerSize": "small",
                "FlowerSmell": "highly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "Red",
                "FruitSize": "small",
                "FruitShape": "Ovoid fleshy berry",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/79.JPG","../assets/7901.JPG"], "ImageCredit": ["Lalithamba","Wibowo Djatmiko"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Bombax ceiba",
                "CommonName": "Red silk cotton tree",
                "Order1":"4",
                "Order2":"43",
                "Order3": 435,
                "FlowerColor": "Red",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "Green, Brown",
                "FruitSize": "large",
                "FruitShape": "Large capsule pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/80.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Bauhinia racemosa",
                "CommonName": "Bidi leaf tree",
                "Order1":"4",
                "Order2":"43",
                "Order3": 436,
                "FlowerColor": "White",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/81.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Caryota urens",
                "CommonName": "Jaggery palm",
                "Order1":"4",
                "Order2":"43",
                "Order3": 437,
                "FlowerColor": "Yellow, brown",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/82.jpg"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Holoptelia integrifolia",
                "CommonName": "Indian elm",
                "Order1":"4",
                "Order2":"44",
                "Order3": 441,
                "FlowerColor": "White, purple",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/83.JPG","../assets/8301.JPG","../assets/8302.JPG"], "ImageCredit": ["A Ajit","A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Bambusa bambos",
                "CommonName": "Indian Thorny bamboo",
                "Order1":"4",
                "Order2":"44",
                "Order3": 442,
                "FlowerColor": "White",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/84.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Bambusa vulgaris",
                "CommonName": "Golden babmboo",
                "Order1":"4",
                "Order2":"44",
                "Order3": 443,
                "FlowerColor": "White",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "",
                "FruitSize": "",
                "FruitShape": "",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/85.JPG"], 
                "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Butea monosperma",
                "CommonName": "Flame of the forest",
                "Order1":"4",
                "Order2":"44",
                "Order3": 444,
                "FlowerColor": "Red",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown",
                "FruitSize": "large",
                "FruitShape": "long flat dry pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": ["../assets/86.JPG","../assets/8603.JPG","../assets/8605.JPG"], 
                "ImageCredit": ["A Ajit","A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Sterculia alata",
                "CommonName": "Buddhas coconut",
                "Order1":"5",
                "Order2":"51",
                "Order3": 511,
                "FlowerColor": "Red",
                "FlowerSize": "Large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Brown",
                "FruitSize": "Large",
                "FruitShape": "Spherical woody splitting open",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/87.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Roystonea regia",
                "CommonName": "Royal palm",
                "Order1":"5",
                "Order2":"52",
                "Order3": 522,
                "FlowerColor": "Yellow",
                "FlowerSize": "Large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Red",
                "FruitSize": "medium",
                "FruitShape": "Round berry",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/88.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Aegle marmelos",
                "CommonName": "Bael",
                "Order1": "",
                "Order2": "",
                "Order3": 524,
                "FlowerColor": "Creamy, green",
                "FlowerSize": "small,large",
                "FlowerSmell": "highly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "Green, yellow",
                "FruitSize": "Large",
                "FruitShape": "Spherical fleshy",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/8901.JPG","../assets/89.JPG","../assets/8902.JPG"], "ImageCredit": ["A Ajit","A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Acacia ferruginea",
                "CommonName": "Rusty Acacia",
                "Order1": "",
                "Order2": "",
                "Order3": 525,
                "FlowerColor": "Creamy",
                "FlowerSize": "small,large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Brown",
                "FruitSize": "medium",
                "FruitShape": "Long flat fleshy pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/90.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Mitragyna parvifolia",
                "CommonName": "Kaim",
                "Order1": "",
                "Order2": "",
                "Order3": 526,
                "FlowerColor": "White",
                "FlowerSize": "large",
                "FlowerSmell": "highly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "green, black",
                "FruitSize": "medium",
                "FruitShape": "Spherical woody capsule",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": ["../assets/91.JPG","../assets/9101.JPG"], "ImageCredit": ["A Ajit","Dinesh Valke"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Schefflera actinophylla",
                "CommonName": "Umbrella tree",
                "Order1": "",
                "Order2": "",
                "Order3": 527,
                "FlowerColor": "Red",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Yellow, red",
                "FruitSize": "medium",
                "FruitShape": "Round berry",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/92.JPG","../assets/9201.JPG"], "ImageCredit": ["A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Cordia sebestina",
                "CommonName": "Scarlet cordia",
                "Order1": "",
                "Order2": "",
                "Order3": 528,
                "FlowerColor": "Orange, Red",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Green",
                "FruitSize": "medium",
                "FruitShape": "Round fleshy",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/93.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Bixa orellana",
                "CommonName": "Lipstick tree",
                "Order1": "",
                "Order2": "",
                "Order3": 529,
                "FlowerColor": "white",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "S",
                "FruitColor": "Black, Red",
                "FruitSize": "large",
                "FruitShape": "Woody pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/94.JPG","../assets/9401.JPG","../assets/9402.JPG"], "ImageCredit": ["A Ajit","Forest & Kim Starr","Rigues"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Pterospermum acerifolium",
                "CommonName": "Kanak champa",
                "Order1": "",
                "Order2": "",
                "Order3": 530,
                "FlowerColor": "creamy, yellow",
                "FlowerSize": "large",
                "FlowerSmell": "highly fragrant",
                "ClusterOrSingle": "S",
                "FruitColor": "Brown",
                "FruitSize": "Large",
                "FruitShape": "woody capsule",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/95.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Castanospermum australe",
                "CommonName": "Black bean",
                "Order1": "",
                "Order2": "",
                "Order3": 531,
                "FlowerColor": "Red, Yellow",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Green, Brown",
                "FruitSize": "LArge",
                "FruitShape": "Large capsule pod",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": ["../assets/96.JPG","../assets/9601.JPG"], "ImageCredit": ["A Ajit","Arthur Chapman"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Adenanthera pavonina",
                "CommonName": "Red bead tree",
                "Order1": "",
                "Order2": "",
                "Order3": 532,
                "FlowerColor": "Yellow",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Green, Brown, Red",
                "FruitSize": "medium",
                "FruitShape": "Curved and Coiled Pods",
                "EdibleFruit": "N",
                "FeatureTags": "",
                "Image": [ "../assets/97.JPG","../assets/9701.JPG"], "ImageCredit": ["A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Moringa oleifera",
                "CommonName": "Drumstick",
                "Order1": "",
                "Order2": "",
                "Order3": 533,
                "FlowerColor": "White",
                "FlowerSize": "small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "green, brown",
                "FruitSize": "large",
                "FruitShape": "long cylindrical dry pod",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": [ "../assets/98.JPG"], "ImageCredit": ["J M Garg"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Manilkara zapota",
                "CommonName": "Chikoo",
                "Order1": "",
                "Order2": "",
                "Order3": 534,
                "FlowerColor": "White",
                "FlowerSize": "small",
                "FlowerSmell": "mildly fragrant",
                "ClusterOrSingle": "C",
                "FruitColor": "Brown",
                "FruitSize": "large",
                "FruitShape": "Round fleshy",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": ["../assets/99.JPG","../assets/9901.JPG"], 
                "ImageCredit": ["A Ajit","H K Arun"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Guazuma ulmifolia",
                "CommonName": "West indian elm",
                "Order1": "",
                "Order2": "",
                "Order3": 523,
                "FlowerColor": "Yellow, green",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Black, brown",
                "FruitSize": "Small",
                "FruitShape": "Spherical woody capsule",
                "EdibleFruit": "Y",
                "FeatureTags": "",
                "Image": ["../assets/10001.JPG","../assets/100.JPG","../assets/10002.JPG"], 
                "ImageCredit": ["A Ajit","A Ajit","A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Schotia brachypetela",
                "CommonName": "Drunk parrot tree",
                "Order1": "",
                "Order2": "",
                "Order3": 535,
                "FlowerColor": "Red",
                "FlowerSize": "large",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "brown",
                "FruitSize": "small",
                "FruitShape": "small woody pod",
                "EdibleFruit": "",
                "FeatureTags": "",
                "Image": [ "../assets/101.JPG"], "ImageCredit": ["A Ajit"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            },
            {
                "ScientificName": "Spondias pinnata",
                "CommonName": "Wild hog plum",
                "Order1": "",
                "Order2": "",
                "Order3": 536,
                "FlowerColor": "creamy, white",
                "FlowerSize": "small",
                "FlowerSmell": "None",
                "ClusterOrSingle": "C",
                "FruitColor": "Green, yellow",
                "FruitSize": "Medium",
                "FruitShape": "round berry",
                "EdibleFruit": "",
                "FeatureTags": "",
                "Image": ["../assets/102.JPG","../assets/102001.JPG"], "ImageCredit": ["A Ajit","Dinesh Valke"], 
		"Description": "This is a sample text which needs to be replaced for each tree later",
                "RareTrees": ""
            }
        ]

        return Observable.of(jsonString);
    }
    
}
